// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace PingPongWebApplication.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190404035912_PingPongWebApplication")]
    partial class PingPongWebApplication
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PingPongWebApplication.Models.Players", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("players");

                    b.HasData(
                        new { Id = 1, Age = 23, CreatedOn = new DateTime(2019, 4, 3, 23, 59, 12, 289, DateTimeKind.Local), Email = "cshah9925@gmail.com", FirstName = "Chandni", LastName = "Shah", ModifiedOn = new DateTime(2019, 4, 3, 23, 59, 12, 291, DateTimeKind.Local), SkillLevel = "Advanced" },
                        new { Id = 2, CreatedOn = new DateTime(2019, 4, 3, 23, 59, 12, 291, DateTimeKind.Local), Email = "jharsh23.hs@gmail.com", FirstName = "Harsh", LastName = "Shah", ModifiedOn = new DateTime(2019, 4, 3, 23, 59, 12, 291, DateTimeKind.Local), SkillLevel = "Beginner" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
